### ISSUE TITLE
Publish new release in github public repo

### ISSUE THREAD

**Issue by felixgillen** [coupies-gmbh/android-sdk#17]

**Comment by felixschul** [comment]
Wir haben das Android SDK bislang noch nie in Maven Central abgelegt, sondern die Partner haben das immer direkt aus dem GIThub-Repo eingebunden. Man kann das bei Maven Central hochladen analog zu CocoaPods, ich hatte mir das mal angeschaut. Kommt sicherlich ganz nett, ist aber nicht unbedingt notwendig. Eine Anleitung, wie wir Android SDK releases bislang veröffentlich haben (das ist etwas ein Prozess) liegt im Wiki.

**Comment by felixgillen** [comment]
Stimmt, das lassen wir dann dieses mal auch würde ich sagen
