### ISSUE TITLE
Kleine Verbesserungen Android Demo-App

### ISSUE THREAD

**Issue by felixschul** [coupies-gmbh/android-sdk#8]
Ein paar Sachen sind für Partner noch verwirren, die müssen wir mal verbessern: 
# Rückmeldung nach Einlösung in Demo-App

Wenn man über die Demo-App einen Bon hochlädt, kommt danach die Meldung "Bon erfolgreich hochgeladen" nativ. Hier wird auch Erfolg angezeigt, wenn der Server eigentlich einen Fehler gemeldet hat. 
- Option 1: Response des Servers auch wirklich verarbeiten. 
- Option 2: Das Ergebnis der Einlösung nicht nativ, sondern hier auch wieder die HTML-Variante anzeigen (also die Response von redeem_html).
# Neuladen des Profil

Man hat keine Chance das Profil neu zu laden und nach Einlösungen deren Status zu sehen. Hier wäre zumindest ein kleiner "Reload"-Button nötig.
# Links verlinken in externen Browser

Wenn man z.B. in "Profil" auf einen seiner Kassenbons klickt, geht der externe Browser auf. Es wäre schön, wenn diese Seite auch im in-app Browser wäre.

**Comment by felixgillen** [comment]
Auf der Profilseite in der Demo-App wird nicht der WebViewclient gesetzt, daher wird der Link in einem externen Browser geöffnet.
http://developer.android.com/guide/webapps/webview.html#AddingWebView

```
myWebView.setWebViewClient(new WebViewClient());
```

Falls möglich sollte diese Funktion in die Abstrakte Klasse, dann wird es einfacher.
